# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Truy cập ở localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
